#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/security-fips
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Security.FIPS.REST)
osgi.jaxrs.resource=true